### ISSUE TITLE
Simulations should capture empirical results

### ISSUE THREAD

**Issue by emdupre** [neurodatascience/fmralign-tutorials#1]
In the [simulations](https://github.com/neurodatascience/fmralign-tutorials/blob/master/simulations.py), we use the "reconstruction ratio" defined by Bazeille and colleagues in their [`fmralign` paper](https://hal.archives-ouvertes.fr/hal-02278663/document).  In the same paper, they show average reconstruction ratios for the IBC dataset across a range of functional alignment methods. For all methods considered, the ratios range from -1 to 1.

In our simulation results, the reconstruction ratio currently ranges from -1 to 0.4 _without smoothing_. If any sort of smoothing is introduced, the minimum reconstruction ratio skews dramatically negative. This is surprising, as fMRI data does have an innate smoothness. 

I'm trying to track down where this discrepancy is arising, but if you have any ideas @jbpoline (or anyone else !), please let me know !

**Comment by jbpoline** [comment]
Raw fmri data may not have a huge amount of smoothness - it depends much more on the signal than on the noise - but yes, there should be some.
Will try jupytext and play with this - hopefull this week !

**Comment by thomasbazeille** [comment]
From what we saw, reconstruction ratios (as well as r2 score btw) can get very negative for real data and we arbitrarily clipped them to -1 which is already a very bad score.

Aligning images after smoothing them will usually give very bad alignments (and bad scores) since specific features used to learn the mappings will be weakened.

On the contrary smoothing reconstructed images will usually improve a bit their reconstruction ratio (even though it may lose some signal specificity)
